### ISSUE TITLE
new version icon

### ISSUE THREAD

**Issue by timoschilling** [jimbojsb/launchrocket#51]
the pref pane should have a update indicator.

**Comment by sesam** [comment]
Do you mean, like under the line "Version 0.7b1" text, you'd want a "New version out now"? Given how many stars etc this repo has, it might be possible to distribute this application through Homebrew, and there you get the `brew upgrade && brew cleanup` features. On the other hand, then the wish quickly appears, to have a notification when there's some tasty upgrades on brew to be had.
