### ISSUE TITLE
Kafka

### ISSUE THREAD

**Issue by tim545** [jimbojsb/launchrocket#53]
Is it possible to start Kafka through LaunchRocket?

**Comment by jimbojsb** [comment]
If it ships with a .plist, yes. Otherwise, still yes, you'd just have to create the plist for it. Assuming you installed Kafka through homebrew it should just work.

**Comment by sesam** [comment]
ping @tim545 (cc @jimbojsb) please close this bug and open another if there's something that doesn't work.
