### ISSUE TITLE
Number of packages is off. 

### ISSUE THREAD

**Issue by kevinSuttle** [jimbojsb/launchrocket#57]
Fresh install, clicked "scan Homebrew".

![screen shot 2015-04-18 at 10 06 44 pm](https://cloud.githubusercontent.com/assets/95672/7217983/584190a6-e617-11e4-9458-9cbbb3a72d84.png)

![screen shot 2015-04-18 at 10 06 17 pm](https://cloud.githubusercontent.com/assets/95672/7217982/584053b2-e617-11e4-94e3-f8a6b7e19f01.png)

**Comment by jimbojsb** [comment]
Looks right to me. LaunchRocket can only control packages that provide a service.

**Comment by kevinSuttle** [comment]
Oh, well, that makes sense. Let me just go over here and finish eating my other foot. :/
