### ISSUE TITLE
how to add a shortcut

### ISSUE THREAD

**Issue by willin** [jimbojsb/launchrocket#66]
how to add a shortcut to desktop, application folder or launchpad?

**Comment by jimbojsb** [comment]
http://lifehacker.com/5743717/create-aliases-for-system-preference-panes-in-mac-os-x

**Comment by willin** [comment]
<img width="1073" alt="2017-01-02 11 00 28" src="https://cloud.githubusercontent.com/assets/1890238/21584213/bd08d71a-d0da-11e6-81df-79520fb8dde2.png">

not found

**Comment by willin** [comment]
```
 ✘  /System/Library/PreferencePanes  sudo find / -name 'LaunchRoket*'
find: /dev/fd/PreferencePanes: No such file or directory
find: /dev/fd/PreferencePanes: No such file or directory
 ✘  /System/Library/PreferencePanes 
```

**Comment by JustinAiken** [comment]
It's in `~/Library/PreferencePanes` 

Everything else the same
