### ISSUE TITLE
launch password

### ISSUE THREAD

**Issue by willin** [jimbojsb/launchrocket#67]
<img width="555" alt="2017-01-03 10 32 53" src="https://cloud.githubusercontent.com/assets/1890238/21598938/0958a526-d1a0-11e6-851a-e2745877a3f1.png">

can it open without password input when there is an application using root?

or just use touch id

**Comment by jimbojsb** [comment]
No it cannot. It uses an insecure applescript hack to invoke scripts as root (read the readme). The alternative is significantly more complicated and requires full code signing. I'd love I if someone wanted to contribute that but I don't plan to.
