### ISSUE TITLE
how to add redmine daemon to the launchrocket

### ISSUE THREAD

**Issue by woei66** [jimbojsb/launchrocket#74]
Hi,

The redmine is a excellent project management and it's open source too.
I installed in it on my Mac os and it works greatly.
I want to know how can I use the launchrocket to stop/start the redmine service.
Does anyone have any idea?
Thank you.
--
The step that I setup and execute redmine on my Mac OS is listed on https://github.com/woei66/installation/blob/master/redmine.md

**Comment by sesam** [comment]
Launchrocket only works with plists. You should find a [guide how to create a plist](https://www.google.com/search?q=guide+how+to+create+a+plist). Afterwards, you can add your .plist file to Launchrocket.

Please close this issue. Thank you, and have a nice day!

**Comment by woei66** [comment]
@sesam got it and thanks a lot
