### ISSUE TITLE
can anyone compile the latest code ?

### ISSUE THREAD

**Issue by tsouhaieb** [jimbojsb/launchrocket#79]

**Comment by huijiewei** [comment]
https://github.com/huijiewei/launchrocket/releases

**Comment by tsouhaieb** [comment]
@huijiewei thanks for responding, can you give us instruction on how you proceeded to compile it, thanks again, and sorry for the inconvenience

**Comment by huijiewei** [comment]
@tsouhaieb I use Xcode
