### ISSUE TITLE
Update release to support Dark Mode in Mojave

### ISSUE THREAD

**Issue by antonmes** [jimbojsb/launchrocket#82]
There is no code change required, just compile with Xcode 10.

[LaunchRocket.prefPane.zip](https://github.com/jimbojsb/launchrocket/files/2077544/LaunchRocket.prefPane.zip)

**Comment by acrogenesis** [comment]
This is how it looks

<img width="758" alt="screen shot 2018-06-13 at 12 00 11 am" src="https://user-images.githubusercontent.com/1312687/41331089-c6f7ca68-6e9c-11e8-99ae-bc34116f6df3.png">

**Comment by uhlhosting** [comment]
It needs support for dark theme only. It seems you use MOjave dark theme and this is adapted to only one theme.
