### ISSUE TITLE
macOS Mojave Unable to start service

### ISSUE THREAD

**Issue by Jaydar** [jimbojsb/launchrocket#87]
macOS Mojave Unable to start service
Click to start invalid

**Comment by Jaydar** [comment]
> You can do it like this:
> 
> 1，>brew services list
> To manage your startup service
> Name Status User Plist
> emacs stopped
> mysql started wangkai /Users/wangkai/Library/LaunchAgents/homebrew.mxcl.mysql.plist
> openvpn started root /Library/LaunchDaemons/homebrew.mxcl.openvpn.plist
> redis stopped
> zookeeper stopped
> 2, >brew services start your service
> Name Status User Plist
> emacs stopped
> mysql started wangkai /Users/wangkai/Library/LaunchAgents/homebrew.mxcl.mysql.plist
> openvpn started root /Library/LaunchDaemons/homebrew.mxcl.openvpn.plist
> redis stopped
> zookeeper stopped

thk!

**Comment by JeferWang** [comment]
虽然命令行能启动，但是我更喜欢这个工具

**Comment by uniquewk** [comment]
> 虽然命令行能启动，但是我更喜欢这个工具

I understand very well

**Comment by iQuinn** [comment]
I found another tools fo homebrew service.
[Website](https://dbngin.com) 
[Github](https://github.com/TablePlus/DBngin)
😁️

**Comment by deartonyz** [comment]
> I found another tools for homebrew service.
> [Website](https://dbngin.com)
> [Github](https://github.com/TablePlus/DBngin)
> 😁️

tks

**Comment by hagedr** [comment]
I wrote a program that can achieve some functions.
[](https://github.com/hagedr/easybrew)

**Comment by deartonyz** [comment]
感觉不错!!!谢谢
